# Generated by Django 6.0.2 on 2026-03-05 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="automatizaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("disponible", models.BooleanField(default=True)),
                ("version", models.CharField(max_length=50)),
                ("url_webhook", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="plan_suscripcion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_suscripcion",
                    models.CharField(
                        choices=[("Mensual", "Mensual"), ("Anual", "Anual")],
                        max_length=10,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "automatizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="afacila.automatizaciones",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="suscripciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activada", models.BooleanField(default=False)),
                ("fecha_suscripcion", models.DateField(auto_now_add=True)),
                ("fecha_caducidad", models.DateField()),
                ("parametros", models.JSONField(blank=True, null=True)),
                (
                    "automatizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="afacila.automatizaciones",
                    ),
                ),
                (
                    "plan_suscripcion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan",
                        to="afacila.plan_suscripcion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suscripciones",
                        to="afacila.usuarios",
                    ),
                ),
            ],
        ),
    ]
