# Generated by Django 6.0.2 on 2026-03-05 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="suscripciones",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suscripciones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RemoveField(
            model_name="suscripciones",
            name="plan_suscripcion",
        ),
        migrations.AddField(
            model_name="suscripciones",
            name="plan",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="suscripciones",
                to="afacila.plan_suscripcion",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="usuarios",
        ),
    ]

