# Generated by Django 6.0.2 on 2026-03-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0002_alter_suscripciones_usuario_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="suscripciones",
            name="id_ejecucion_n8n",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
