# Generated by Django 6.0.2 on 2026-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0003_suscripciones_id_ejecucion_n8n"),
    ]

    operations = [
        migrations.AddField(
            model_name="automatizaciones",
            name="url_webhook_parada",
            field=models.URLField(
                default="http://localhost:5678/webhook-test/parar_automatizacion_1"
            ),
            preserve_default=False,
        ),
    ]
