# Generated by Django 6.0.2 on 2026-03-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0004_automatizaciones_url_webhook_parada"),
    ]

    operations = [
        migrations.CreateModel(
            name="vistaprevia_post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.TextField(blank=True, null=True)),
                ("imagen", models.CharField(blank=True, max_length=255500, null=True)),
                ("fecha_creacion", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
