# Generated by Django 6.0.2 on 2026-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0005_vistaprevia_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vistaprevia_post",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
