# Generated by Django 6.0.2 on 2026-03-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0006_alter_vistaprevia_post_imagen"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="posts/"),
                ),
                ("texto", models.TextField(blank=True, null=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
