# Generated by Django 6.0.2 on 2026-03-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0007_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="automatizaciones",
            old_name="url_webhook_parada",
            new_name="url_webhook_postear",
        ),
    ]
