# Generated by Django 6.0.2 on 2026-03-21 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "afacila",
            "0008_rename_url_webhook_parada_automatizaciones_url_webhook_postear",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("url", models.URLField()),
                (
                    "automatizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="afacila.automatizaciones",
                    ),
                ),
            ],
        ),
    ]
