# Generated by Django 6.0.2 on 2026-03-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0009_webhook"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webhook",
            name="automatizacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="webhook",
                to="afacila.automatizaciones",
            ),
        ),
    ]
