# Generated by Django 6.0.2 on 2026-03-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0010_alter_webhook_automatizacion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="automatizaciones",
            name="url_webhook_postear",
        ),
    ]
