# Generated by Django 6.0.2 on 2026-03-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0011_remove_automatizaciones_url_webhook_postear"),
    ]

    operations = [
        migrations.AddField(
            model_name="automatizaciones",
            name="url_demo_webhook",
            field=models.URLField(blank=True, null=True),
        ),
    ]
