# Generated by Django 6.0.2 on 2026-03-22 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0013_perfil_usuario_delete_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfil_usuario",
            old_name="max_ejecuciones_demo",
            new_name="ejecuciones_demo",
        ),
        migrations.RenameField(
            model_name="perfil_usuario",
            old_name="usuario",
            new_name="user",
        ),
    ]
