# Generated by Django 6.0.2 on 2026-03-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "afacila",
            "0014_rename_max_ejecuciones_demo_perfil_usuario_ejecuciones_demo_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfil_usuario",
            old_name="tiene_subscription",
            new_name="tiene_subscripcion",
        ),
    ]
