# Generated by Django 6.0.2 on 2026-03-22 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("afacila", "0015_rename_tiene_subscription_perfil_usuario_tiene_subscripcion"),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfil_usuario",
            old_name="tiene_subscripcion",
            new_name="tiene_subscripciones",
        ),
    ]
