# Generated by Django 6.0.2 on 2026-03-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "afacila",
            "0016_rename_tiene_subscripcion_perfil_usuario_tiene_subscripciones",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="perfil_usuario",
            old_name="tiene_subscripciones",
            new_name="tiene_subscripcion",
        ),
    ]
