# Generated by Django 6.0.2 on 2026-03-22 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "afacila",
            "0017_rename_tiene_subscripciones_perfil_usuario_tiene_subscripcion",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil_usuario",
            name="es_demo",
        ),
        migrations.RemoveField(
            model_name="perfil_usuario",
            name="tiene_subscripcion",
        ),
        migrations.AddField(
            model_name="perfil_usuario",
            name="automatizacion",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="afacila.automatizaciones",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="perfil_usuario",
            name="limite_ejecuciones_demo",
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name="perfil_usuario",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="perfil_usuario",
            constraint=models.UniqueConstraint(
                fields=("user", "automatizacion"), name="unique_user_automatizacion"
            ),
        ),
    ]
